Feature/make json indentation configurable
Gradiant/pyodi pull request #171
Opened 2021-12-13 18:11 UTC by philenius

Thank you for providing this great library. I had the issue that merging two COCO files (each 2.8 MB in size) resulted in a 19 MB large COCO JSON file (too large in my opinion). The huge difference in size was caused by the JSON indentation which is set to 2 spaces:

https://github.com/Gradiant/pyodi/blob/d48b39c23b249f796291a5904a0e936b63367ab0/pyodi/apps/coco/coco_merge.py#L90-L91

**Previously:**

Merging two COCO files with fixed indentation of 2 spaces:

```python
from pyodi.apps import coco
coco.coco_merge('coco_annotations1.json', 'coco_annotations2.json', 'output.json')
```

resulted in:

```
-rw-rw-r--  1 phil phil 2,8M Dez 13 18:59 coco_annotations1.json
-rw-rw-r--  1 phil phil 2,8M Dez 13 18:59 coco_annotations2.json
-rw-rw-r--  1 phil phil  19M Dez 13 19:01 output.json
```

**With my changes:**

Merging the same two COCO files with indentation disabled by setting `json_indentation=None`:

```python
from pyodi.apps import coco
coco.coco_merge('coco_annotations1.json', 'coco_annotations2.json', 'output.json', json_indentation=None)
```

results in:

```
-rw-rw-r--  1 phil phil 2,8M Dez 13 18:59 coco_annotations1.json
-rw-rw-r--  1 phil phil 2,8M Dez 13 18:59 coco_annotations2.json
-rw-rw-r--  1 phil phil 5,6M Dez 13 19:01 output.json
```

2021-12-13 18:48 UTC, daavoo requested changes
Thanks for the contribution!

I would suggest adding a simple check (in https://github.com/Gradiant/pyodi/blob/master/tests/apps/test_coco_merge.py) ensuring that `indent` is passed to `json.dump`.

2021-12-13 18:48 UTC, daavoo commented on pyodi/apps/coco/coco_merge.py
> +    json_indentation: Union[int, None] = 2,
```suggestion
    indent: Optional[int] = None,
```

2021-12-13 18:48 UTC, daavoo commented on pyodi/apps/coco/coco_merge.py
> +        json_indentation: If set to a non-negative integer, then JSON array elements and object members will be pretty-printed with that indent level. An indent level of `0` will only insert newlines
```suggestion
        indent: Argument passed to `json.dump`. See https://docs.python.org/3/library/json.html#json.dump.
```

2021-12-13 21:06 UTC, daavoo approved these changes

2021-12-14 08:01 UTC, mmeendez8 approved these changes

2021-12-14 08:01 UTC, merged